id = 2
name = "nimbos_2"
vm_type = 1
cpu_num = 1
phys_cpu_sets = [2]
entry_point = 0x8008_0000

# The location of image: "memory" | "fs"
image_location = "fs" 
kernel_path = "arm_tiny_vm_0x80080000.bin"
kernel_load_addr = 0x8008_0000

# bios_path = ""
# bios_load_addr = 0
# ramdisk_path = ""
# ramdisk_load_addr = 0
# disk_path = ""
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    [0x8000_0000, 0x100_0000, 0x7, 0],   # Low RAM		    16M 0b00111 R|W|EXECUTE
]

# Emu_devices
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig
emu_devices = []

# Pass-through devices
# Name Base-Ipa Base-Pa Length Alloc-Irq
passthrough_devices = [
    # ["intc@8000000", 0x800_0000, 0x800_0000, 0x50_000, 0x1],
    ["pl011@9000000", 0x900_0000, 0x904_0000, 0x1000, 0x1],
    # ["pl031@9010000", 0x901_0000, 0x901_0000, 0x1000, 0x1],
    # ["pl061@9030000", 0x903_0000, 0x903_0000, 0x1000, 0x1],
    # # a003000.virtio_mmio virtio_mmio@a003000 
    # # a003200.virtio_mmio virtio_mmio@a003200
    # ["virtio_mmio", 0xa00_0000, 0xa00_0000, 0x4000, 0x1],
]