# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "starry"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# Guest vm physical cpu sets.
phys_cpu_sets = [1]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x4008_0000
# The location of image: "memory" | "fs".
# Load from file system.
image_location = "fs"
# The file path of the kernel image.
kernel_path = "starry-aarch64.bin"
# The load address of the kernel image.
kernel_load_addr = 0x4008_0000
# The file path of the BIOS image.
dtb_load_addr = 0x4000_0000
# The load address of the BIOS image.
dtb_path = "starry-aarch64.bin"

## The file path of the ramdisk image.
# ramdisk_path = ""
## The load address of the ramdisk image.
# ramdisk_load_addr = 0
## The path of the disk image.
# disk_path = "disk.img"

# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    [0x4000_0000, 0x100_0000, 0x7, 0], # Low RAM		    16M 0b00111 R|W|EXECUTE
]

#
# Device specifications
#
[devices]
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = []

# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [
    ["intc@8000000", 0x800_0000, 0x800_0000, 0x50_000, 0x1],
    ["pl011@9000000", 0x900_0000, 0x900_0000, 0x1000, 0x1],
    ["pl031@9010000", 0x901_0000, 0x901_0000, 0x1000, 0x1],
    ["pl061@9030000", 0x903_0000, 0x903_0000, 0x1000, 0x1],
    # a003000.virtio_mmio virtio_mmio@a003000
    # a003200.virtio_mmio virtio_mmio@a003200
    ["virtio_mmio", 0xa00_0000, 0xa00_0000, 0x4000, 0x1],
]