id = 1
name = "arceos"
vm_type = 1
cpu_num = 4
# phys_cpu_sets = [15, 15]
phys_cpu_sets = [0x7, 0x7, 0x7, 0x7]
# phys_cpu_sets = [0x7, 0x7]
# phys_cpu_sets = [0x3, 0x3]
# phys_cpu_sets = [1]
entry_point = 0x8020_0000
# kernel_path = "arceos-riscv64-parallel-debug.bin"
kernel_path = "arceos-riscv64-parallel-trace-hartx4.bin"
kernel_load_addr = 0x8020_0000
# Memory regions with format (`base_paddr`, `size`, `flags`).
memory_regions = [
#    [0x8000_0000, 0x100_0000, 0xf], # Low RAM		16M	0b1111  R|W|EXECUTE|U
# arceos parallel need 64MB ram
    [0x8000_0000, 0x400_0000, 0xf], # Low RAM		64M	0b1111  R|W|EXECUTE|U
    [0x0c00_0000, 0x21_0000, 0x13], # PLIC  0x21_0000	0b10011 R|W|DEVICE
    [0x1000_0000, 0x1000, 0x13],    # UART	     4K	0b10011 R|W|DEVICE
]

# Emu_devices
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig
emu_devices = [
]
