id = 1
name = "nimbos"
vm_type = 1
cpu_set = 2
entry_point = 0x8000
bios_path = "rvm-bios.bin"
bios_load_addr = 0x8000
kernel_path = "nimbos-x86.bin"
kernel_load_addr = 0x20_0000
# ramdisk_path = ""
# ramdisk_load_addr = 0
# disk_path = ""
# Memory regions with format (`base_paddr`, `size`, `flags`).
memory_regions = [
    [0x0000_0000, 0x100_0000, 0x7],   # Low RAM		16M	0b111
    [0xfec0_0000, 0x1000, 0x17],      # IO APIC		4K	0b10111
    [0xfee0_0000, 0x1000, 0x17],      # Local APIC	4K	0b10111
    [0xfed0_0000, 0x1000, 0x17],      # HPET 		4K  0b10111
]