id = 1
name = "linux"
vm_type = 1
cpu_set = 2
cpu_num = 1
entry_point = 0x1008_0000
# kernel_path = "linux-aarch64.bin"
kernel_load_addr = 0x1008_0000
dtb_load_addr = 0x1000_0000

# The location of image: "memory" | "fs"
# load from memory
image_location = "memory" 
kernel_path = "linux-rk3588-aarch64.bin"
kernel_size = 0x400_0000
dtb_path = "linux-rk3588.dtb"
dtb_size = 0x8_0000

# load from file system
# image_location = "fs"
# kernel_path = "arceos-aarch64.bin"

platform = "aarch64-rk3588j"
arch = "aarch64"
# ramdisk_path = ""
# ramdisk_load_addr = 0
# disk_path = "disk.img"
# Memory regions with format (`base_paddr`, `size`, `flags`).
memory_regions = [
    [0x0,0x10_f000,0x37], # passthrough uncahed 
    [0x11_0000,0xf_0000, 0x17], #ramoops
    [0x10_f000,0x1000,0x17],#sram
    [0x940_0000,0x76c00000, 0x7],#ram 3G 
    [0xfb00_0000,0x200000,0x17], # gpu
    [0xfd00_0000,0x2000000,0x17], # uart8250 UART
    [0xfc00_0000,0x1000000,0x17], #usb
]

# Emu_devices
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig
emu_devices = [
]
